spring.cloud.config.server.encrypt.enabled: false

####################################
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/carnellj/config-repo/
#          searchPaths: licensingservice,organizationservice
#          username: native-cloud-apps
#          password: 0ffended


####
#File Configuration
####
server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/martineze/Documents/Projects/IntelliJ/GatewaySample/confsrv/src/main/resources/config/licensingservice

#Setting logging levels
logging:
  level:
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
