spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8081

#Setting the logging levels for the service
logging:
  level:
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
